# Configuration file for travis-ci.org. Travis is a /continuous integration/ tool that runs tests.
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  # not supported yet by Travis
  #- "3.7"
  - "pypy"
  - "pypy3"
sudo: false
addons:
  apt:
    packages:
    - curl
install:
 # Install python-coveralls
 - pip install coveralls
 # pillow is (only) used for examples/map.py
 - pip install pillow
script:
  # run tests/alltests.py (which runs the actual tests)
  # wrap in coverage, which reports the amount of code is covered by the tests.
  - coverage run --source=nbt tests/alltests.py
after_success:
  # Send test coverage results to https://coverage.io/
  coveralls
